"""Initial migration

Revision ID: 0acd9c237907
Revises: 3c22f8751dea
Create Date: 2024-08-30 17:40:36.908631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0acd9c237907'
down_revision: Union[str, None] = '3c22f8751dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraper_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_metadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scraper_friendly_name', sa.VARCHAR(), autoincrement=False, nullable=False, comment='A human-friendly name for the scraper'),
    sa.Column('scraper_id', postgresql.ENUM('APM', 'MAHER', name='scraper'), autoincrement=False, nullable=True, comment='Unique identifier for the scraper'),
    sa.Column('terminal_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Terminal ID associated with the scraper'),
    sa.Column('scrape_frequency_hours', sa.INTEGER(), autoincrement=False, nullable=False, comment='Frequency of scraping in hours'),
    sa.Column('last_scraped_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='The last time the scraper was run, in UTC'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Indicates whether the scraper is currently active'),
    sa.Column('scraper_version', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Version of the scraper'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Timestamp when the scraper was created, in UTC'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Timestamp when the scraper was last updated, in UTC'),
    sa.PrimaryKeyConstraint('id', name='scraper_metadata_pkey')
    )
    # ### end Alembic commands ###
