"""Initial migration

Revision ID: 1efb08695203
Revises: 4181b81fbcc5
Create Date: 2024-11-19 15:08:20.317761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1efb08695203'
down_revision: Union[str, None] = '4181b81fbcc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container_status_table', sa.Column('delivery_date', sa.String(), nullable=True))
    op.drop_column('container_status_table', 'delivery_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container_status_table', sa.Column('delivery_data', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('container_status_table', 'delivery_date')
    # ### end Alembic commands ###
