"""Initial migration

Revision ID: 4181b81fbcc5
Revises: 476151f91c61
Create Date: 2024-11-19 15:06:18.620277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4181b81fbcc5'
down_revision: Union[str, None] = '476151f91c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container_status_table', sa.Column('delivery_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('container_status_table', 'delivery_data')
    # ### end Alembic commands ###
