"""remove previous data and retry count

Revision ID: 4a1151ba0645
Revises: c340a917cfac
Create Date: 2024-11-28 13:50:37.875914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a1151ba0645'
down_revision: Union[str, None] = 'c340a917cfac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment_logs', 'retry_count')
    op.drop_column('shipment_logs', 'previous_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment_logs', sa.Column('previous_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('shipment_logs', sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
