"""Initial migration

Revision ID: 4f8e95c9e567
Revises: ebc4f3945ba2
Create Date: 2024-09-04 12:28:08.974731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8e95c9e567'
down_revision: Union[str, None] = 'ebc4f3945ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_tokens_id', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.alter_column('container_status_table', 'last_updated_availability',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('container_status_table', 'vessel_name')
    op.add_column('shipments', sa.Column('vessel_name', sa.String(length=25), nullable=True))
    op.add_column('shipments', sa.Column('vessel_orig_eta', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'vessel_orig_eta')
    op.drop_column('shipments', 'vessel_name')
    op.add_column('container_status_table', sa.Column('vessel_name', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.alter_column('container_status_table', 'last_updated_availability',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('auth_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_tokens_pkey')
    )
    op.create_index('ix_auth_tokens_id', 'auth_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
