"""Initial migration

Revision ID: 651e6f6fb7fb
Revises: a4cbfdd36e13
Create Date: 2024-09-10 13:12:50.835397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651e6f6fb7fb'
down_revision: Union[str, None] = 'a4cbfdd36e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('container_status_table', 'port',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('container_status_table', 'port',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
