"""Initial migration

Revision ID: 77be956ea2a8
Revises: 
Create Date: 2024-08-30 20:04:28.477737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77be956ea2a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_tokens_id', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_table('shipment_table')
    op.add_column('container_status_table', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('container_status_table', sa.Column('shipment_id', sa.Integer(), nullable=True))
    op.add_column('container_status_table', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('container_status_table', sa.Column('port', sa.String(), nullable=False))
    op.add_column('container_status_table', sa.Column('terminal', sa.String(), nullable=False))
    op.add_column('container_status_table', sa.Column('container_number', sa.String(), nullable=False))
    op.add_column('container_status_table', sa.Column('available', sa.String(), nullable=False))
    op.add_column('container_status_table', sa.Column('usda_status', sa.String(), nullable=True))
    op.add_column('container_status_table', sa.Column('last_free_date', sa.String(), nullable=True))
    op.add_column('container_status_table', sa.Column('location', sa.String(), nullable=True))
    op.add_column('container_status_table', sa.Column('custom_release_status', sa.String(), nullable=True))
    op.add_column('container_status_table', sa.Column('carrier_release_status', sa.String(), nullable=True))
    op.add_column('container_status_table', sa.Column('demurrage_amount', sa.String(), nullable=True))
    op.add_column('container_status_table', sa.Column('vessel_name', sa.String(length=25), nullable=True))
    op.add_column('container_status_table', sa.Column('yard_terminal_release_status', sa.String(), nullable=True))
    op.add_column('container_status_table', sa.Column('last_updated_availability', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'container_status_table', ['container_number'])
    op.create_foreign_key(None, 'container_status_table', 'shipments', ['shipment_id'], ['shipment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'container_status_table', type_='foreignkey')
    op.drop_constraint(None, 'container_status_table', type_='unique')
    op.drop_column('container_status_table', 'last_updated_availability')
    op.drop_column('container_status_table', 'yard_terminal_release_status')
    op.drop_column('container_status_table', 'vessel_name')
    op.drop_column('container_status_table', 'demurrage_amount')
    op.drop_column('container_status_table', 'carrier_release_status')
    op.drop_column('container_status_table', 'custom_release_status')
    op.drop_column('container_status_table', 'location')
    op.drop_column('container_status_table', 'last_free_date')
    op.drop_column('container_status_table', 'usda_status')
    op.drop_column('container_status_table', 'available')
    op.drop_column('container_status_table', 'container_number')
    op.drop_column('container_status_table', 'terminal')
    op.drop_column('container_status_table', 'port')
    op.drop_column('container_status_table', 'date')
    op.drop_column('container_status_table', 'shipment_id')
    op.drop_column('container_status_table', 'id')
    op.create_table('shipment_table',
    sa.Column('shipment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('voyage_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('continue_scraping', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_scraped_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_scrape_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('terminal_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('container_number', sa.VARCHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('master_bol_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('house_bol_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('vessel_name', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('shipment_id', name='shipment_table_pkey')
    )
    op.create_table('auth_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_tokens_pkey')
    )
    op.create_index('ix_auth_tokens_id', 'auth_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
