"""Initial migration

Revision ID: 829b87670bb0
Revises: 
Create Date: 2024-09-28 04:41:06.402639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '829b87670bb0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notify')
    op.drop_column('shipments', 'run_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('run_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('notify',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shipment_ids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notify_name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='notify_pkey')
    )
    # ### end Alembic commands ###
