"""Initial migration

Revision ID: a21220b6658d
Revises: 3810fc84de11
Create Date: 2024-11-20 17:35:18.574508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a21220b6658d'
down_revision: Union[str, None] = '3810fc84de11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container_status_table', sa.Column('delivery_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('container_status_table', 'delivery_date')
    # ### end Alembic commands ###
