"""Initial migration

Revision ID: b42564f2ef28
Revises: 
Create Date: 2024-08-30 23:44:57.581375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b42564f2ef28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('container_status_table', 'shipment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('container_status_table', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('container_status_table', 'last_updated_availability',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('container_status_table_container_number_key', 'container_status_table', type_='unique')
    op.drop_column('container_status_table', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container_status_table', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('container_status_table_container_number_key', 'container_status_table', ['container_number'])
    op.alter_column('container_status_table', 'last_updated_availability',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('container_status_table', 'date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('container_status_table', 'shipment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
