"""Initial migration

Revision ID: c193425465f0
Revises: b9f3e4dcebe4
Create Date: 2024-09-06 11:38:11.654902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c193425465f0'
down_revision: Union[str, None] = 'b9f3e4dcebe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_tokens_id', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.add_column('container_status_table', sa.Column('additional_info', sa.JSON(), nullable=True))
    op.drop_column('container_status_table', 'usda_status')
    op.drop_column('container_status_table', 'shipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container_status_table', sa.Column('shipment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('container_status_table', sa.Column('usda_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('container_status_table', 'additional_info')
    op.create_table('auth_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_tokens_pkey')
    )
    op.create_index('ix_auth_tokens_id', 'auth_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
