"""Add vessel_name to container_status_table

Revision ID: d9e1627a9dc0
Revises: e7e0f0b077a8
Create Date: 2024-08-30 17:11:01.278919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e1627a9dc0'
down_revision: Union[str, None] = 'e7e0f0b077a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
