"""Initial migration

Revision ID: e820bfde6cd6
Revises: b42564f2ef28
Create Date: 2024-08-31 00:59:03.065346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e820bfde6cd6'
down_revision: Union[str, None] = 'b42564f2ef28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container_status_table', sa.Column('last_free_day', sa.String(), nullable=True))
    op.add_column('container_status_table', sa.Column('type_code', sa.String(), nullable=True))
    op.add_column('container_status_table', sa.Column('transit_state', sa.String(), nullable=True))
    op.add_column('container_status_table', sa.Column('departed_terminal', sa.String(), nullable=True))
    op.add_column('container_status_table', sa.Column('holds', sa.String(), nullable=True))
    op.add_column('container_status_table', sa.Column('charges', sa.String(), nullable=True))
    op.add_column('container_status_table', sa.Column('demurage', sa.String(), nullable=True))
    op.add_column('container_status_table', sa.Column('line', sa.String(), nullable=True))
    op.drop_column('container_status_table', 'last_free_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container_status_table', sa.Column('last_free_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('container_status_table', 'line')
    op.drop_column('container_status_table', 'demurage')
    op.drop_column('container_status_table', 'charges')
    op.drop_column('container_status_table', 'holds')
    op.drop_column('container_status_table', 'departed_terminal')
    op.drop_column('container_status_table', 'transit_state')
    op.drop_column('container_status_table', 'type_code')
    op.drop_column('container_status_table', 'last_free_day')
    # ### end Alembic commands ###
